### ISSUE TITLE
Request for a feature for getting the response text to clipboard and pop out a notification

### ISSUE THREAD

**Issue by ChunwuZhu** [yanxiaodi/vs-code-revision#7]
Dear ReVision developer,

Could you provide a feature to get the response text to the clipboard? The current function for revise and insert will have several seconds of a pause without any notification. When the Chatgpt has returned the response text, it will interrupt the process of writing by displacing the cursor to the response text. I wonder if you can provide a feature to automatically send the response text to the clipboard and show the response text somewhere such as notification or sidebar, such that we can decide where we insert the new text or not by pasting the response text. Thanks!

**Comment by yanxiaodi** [comment]
Yes the current implementation is that you press the keys then wait for a while - because the extension needs to know where to insert the text. If you are writing at the same time, the cursor position would change so it would insert the text on the wrong position. It basically follows the same approach as my last VS Code extension Translator Helper. If you prefer to store the text in the clipboard, I can provide an option in the settings. Can do it in the next few weeks. Sorry my spare time is limited so cannot guarantee the date. Thanks for your feedback!

**Comment by ChunwuZhu** [comment]
> Yes the current implementation is that you press the keys then wait for a while - because the extension needs to know where to insert the text. If you are writing at the same time, the cursor position would change so it would insert the text on the wrong position. It basically follows the same approach as my last VS Code extension Translator Helper. If you prefer to store the text in the clipboard, I can provide an option in the settings. Can do it in the next few weeks. Sorry my spare time is limited so cannot guarantee the date. Thanks for your feedback!

Thank you very much!

**Comment by yanxiaodi** [comment]
@ChunwuZhu Updated to add this feature. You should be able to download the latest version shortly. If you have any issues regarding this, please reopen the issue. Thanks for your feedback!
